export const routerNames = {
  HOME: "/",
  SHOP: "/shop",
  BLOG: "/blog",
  CONTACT: "/contact",
  ABOUT: "/about",
  DOG: "/dog",
  CAT: "/cat",
  FISH: "/fish",
  RABBIT: "/rabbit",
  TURTLE: "/turtle",
  OTHER: "/other",
  CAREER: "/career",
  HISTORY: "/history",
  ORGANIZATION: "/organization",
  INTRODUCTION: "/introduction", 
};
