export const routerNames = {
  HOME: "/",
  PRODUCT: "/product",
  CATEGORY: "/category",
  PRODUCT_DETAIL: "/product/product-detail/[id]",
  CONTACT: "/contact",
  DOG: "/dog",
  CAT: "/cat",
  FISH: "/fish",
  RABBIT: "/rabbit",
  TURTLE: "/turtle",
  BIRD: "/bird",
  OTHER: "/other",
  CAREER: "/career",
  HISTORY: "/history",
  ORGANIZATION: "/organization",
  INTRODUCTION: "/introduction",
};
