export const routerNames = {
  HOME: "/",
  PRODUCT: "/product",
  CATEGORY: "/category",
  PRODUCT_DETAIL: "/product/product-detail/[id]",
  CONTACT: "/contact",
  DOG: "/dog",
  CAT: "/cat",
  FISH: "/fish",
  RABBIT: "/rabbit",
  TURTLE: "/turtle",
  BIRD: "/bird",
  HAMSTER: "/hamster",
  CHICKEN: "/chicken",
  CAREER: "/career",
  HISTORY: "/history",
  ORGANIZATION: "/organization",
  INTRODUCTION: "/introduction",
  CARE_TOOLS: "/care-tools",
  MEDICATION: "/medication",
  ACCESSORIES: "/accessories",
  FOOD_NUTRITION: "/food-nutrition",
};
